import { backgroundConstructor, backgroundModule } from './background-plugin-runtime';
export type ParticleImageRenderer = import('./particle-image-startup').ParticleImageRenderer;
export const ParticleImageRenderer = backgroundConstructor<typeof import('./particle-image-startup').ParticleImageRenderer>('particle-image', 'ParticleImageRenderer');
export type GlowHorizonRenderer = import('./startup-background-renderers').GlowHorizonRenderer;
export const GlowHorizonRenderer = backgroundConstructor<typeof import('./startup-background-renderers').GlowHorizonRenderer>('glow-horizon', 'GlowHorizonRenderer');
export type HeavenlyCloudRenderer = import('./startup-background-renderers').HeavenlyCloudRenderer;
export const HeavenlyCloudRenderer = backgroundConstructor<typeof import('./startup-background-renderers').HeavenlyCloudRenderer>('heavenly-cloud', 'HeavenlyCloudRenderer');
export type AuroraIonosphereRenderer = import('./startup-background-renderers').AuroraIonosphereRenderer;
export const AuroraIonosphereRenderer = backgroundConstructor<typeof import('./startup-background-renderers').AuroraIonosphereRenderer>('aurora-ionosphere', 'AuroraIonosphereRenderer');
export type MilkyWayRenderer = import('./startup-background-renderers').MilkyWayRenderer;
export const MilkyWayRenderer = backgroundConstructor<typeof import('./startup-background-renderers').MilkyWayRenderer>('milky-way', 'MilkyWayRenderer');
export type MountainRenderer = import('./startup-background-renderers').MountainRenderer;
export const MountainRenderer = backgroundConstructor<typeof import('./startup-background-renderers').MountainRenderer>('mountain', 'MountainRenderer');
export type BlinkingSquaresRenderer = import('./blinking-squares-host').BlinkingSquaresRenderer;
export const BlinkingSquaresRenderer = backgroundConstructor<typeof import('./blinking-squares-host').BlinkingSquaresRenderer>('blinking-squares', 'BlinkingSquaresRenderer');
export type CloudTrainRenderer = import('./startup-background-renderers').CloudTrainRenderer;
export const CloudTrainRenderer = backgroundConstructor<typeof import('./startup-background-renderers').CloudTrainRenderer>('cloud-train', 'CloudTrainRenderer');
export type PixelSculptRenderer = import('./pixel-sculpt-renderer').PixelSculptRenderer;
export const PixelSculptRenderer = backgroundConstructor<typeof import('./pixel-sculpt-renderer').PixelSculptRenderer>('pixel-sculpt', 'PixelSculptRenderer');
export type BlackHoleRenderer = import('./startup-background-renderers').BlackHoleRenderer;
export const BlackHoleRenderer = backgroundConstructor<typeof import('./startup-background-renderers').BlackHoleRenderer>('black-hole', 'BlackHoleRenderer');
export const populateGlowHorizonLayer: typeof import('./startup-background-renderers').populateGlowHorizonLayer = (...args) => (backgroundModule('glow-horizon').exports.populateGlowHorizonLayer as typeof import('./startup-background-renderers').populateGlowHorizonLayer)(...args);
